version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=production
      - LOG_LEVEL=info
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
